server:
  port: 11020
management:
  port: 11021
spring:
  application:
    name: hystrix-turbine-stream
#  kafka:
#    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
turbine:
  app-config: enreka-consumer-feign-hystrix-stream
  cluster-name-expression: new String("default")
  combine-host-port: true
spring.cloud.stream.kafka.binder.brokers : localhost:9092
spring.cloud.stream.kafka.binder.zk-nodes : localhost:2181
spring.cloud.stream.kafka.binder.minPartitionCount : 1
spring.cloud.stream.kafka.binder.autoCreateTopics: true
spring.cloud.stream.kafka.binder.autoAddPartitions: false
hystrix.stream.dashboard.intervalInMilliseconds: 2000
debug: true