spring:
  application:
    name: enreka-consumer-feign-hystrix
server:
  port: 3003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
