server:
  port: 10220
spring:
  application:
    name: enreka-consumer-feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
debug: true
feign:
  hystrix:
    enabled: true
