server:
  port: 8081
  spring:
  application:
    name: eureka_stream_kafka_consumer
  cloud:
    instance-count: 1
    instance-index: 0
    kafka:
      binder:
        brokers: localhost:9092
        zk-nodes: localhost:2182
        auto-add-partitions: true
        auto-create-topics: true
        min-partition-count: 1
    stream:
      bindings:
        input:
          destination: event-demo
          group: s1
        consumer:
          autoCommitOffset: false
          concurrency: 1
          partitioned: false