server:
  port: 10250
spring:
  application:
    name: eureka-consumer-sleuth-stream
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
spring.sleuth.sampler.percentage: 1
