server:
  port: 3004
spring:
  application:
    name: eureka-consumer-sleuth-stream
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

