server:
  port: 10250
spring:
  application:
    name: eureka-consumer-sleuth-stream
eureka:
  client:
    service-url:
      defaultZone: http://10.255.229.123:8761/eureka/
spring.sleuth.sampler.percentage: 1
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
spring.cloud.stream.kafka.binder.brokers: 10.255.229.123:9092
spring.cloud.stream.kafka.binder.zk-nodes: 10.255.229.123:2181

#  kafka:
#    bootstrap-servers: localhost:9092