server:
  port: 10100
spring:
  application:
    name: eureka-client
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/