server:
  port: 9411
spring:
  application:
    name: zipkin-server-stream
  kafka:
    bootstrap-servers: localhost:9092
debug: true
zipkin.storage.type: elasticsearch
zipkin.storage.elasticsearch.hosts: localhost:9300
zipkin.storage.elasticsearch.cluster: es
zipkin.storage.elasticsearch.index: zipkinstore
zipkin.storage.elasticsearch.index-shards: 5
zipkin.storage.elasticsearch.index-replicas: 2
#elasticsearch config
#zipkin:
#  storage:
#    type: elasticsearch
#  elasticsearch:
#    hosts: 10.82.0.237:9300
#    cluster: es
#    index: zipkin
#    index-shards: 5
#    index-replicas: 1
