server:
  port: 10100
spring:
  application:
    name: eureka-client
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://10.255.229.123:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
