server:
  port: 10260
spring:
  application:
    name: enreka-consumer-feign-hystrix-stream
#  kafka:
#    bootstrap-servers: 10.255.229.123:9092
eureka:
  client:
    service-url:
      defaultZone: http://10.255.229.123:8761/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
debug: true
hystrix.stream.dashboard.intervalInMilliseconds: 2000

spring.cloud.stream.kafka.binder.brokers : 10.255.229.123:9092
spring.cloud.stream.kafka.binder.zk-nodes : 10.255.229.123:2181